[project]
name = "202601-snowysunday"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.2",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
